HamburgerOrder/Areas/Admin/Controllers/DashboardController.cs
using HamburgerOrder.Data;
using HamburgerOrder.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HamburgerOrder.Areas.Admin.Controllers
{
    public class DashboardController : AdminBaseController
    {
        private readonly ApplicationDbContext _db;
        public DashboardController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var products = new ProductsViewModel()
            {
                Menus = _db.Menus.ToList(),
                Extras = _db.Extras.ToList()
            };

            return View(products);
        }

        public IActionResult AddMenu()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddMenu(MenuViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Menu menu = new Menu()
                {
                    Name = vm.Name,
                    Price = vm.Price
                };

                _db.Menus.Add(menu);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View();
        }
        public IActionResult UpdateMenu(int id)
        {
            var menu = _db.Menus.Find(id);
            if (menu == null)
                return NotFound();

            MenuViewModel vm = new MenuViewModel()
            {
                Name = menu.Name,
                Price = menu.Price
            };
            TempData["menu"] = id;
            return View(vm);
        }
        [HttpPost]
        public IActionResult UpdateMenu(MenuViewModel vm)
        {
            int id = Convert.ToInt32(TempData["menu"]);
            var menu = _db.Menus.Find(id);

            if(menu is not null && ModelState.IsValid)
            {
                menu.Name = vm.Name;
                menu.Price = vm.Price;

                _db.Menus.Update(menu);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        public IActionResult DeleteMenu(int id)
        {
            var menu = _db.Menus.Find(id);
            _db.Menus.Remove(menu);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult AddExtra()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddExtra(ExtraViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Extra extra = new Extra()
                {
                    Name = vm.Name,
                    Price = vm.Price
                };

                _db.Extras.Add(extra);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult UpdateExtra(int id)
        {
            var extra = _db.Extras.Find(id);
            if (extra == null)
                return NotFound();

            ExtraViewModel vm = new ExtraViewModel()
            {
                Name = extra.Name,
                Price = extra.Price
            };
            TempData["extra"] = id;
            return View(vm);
        }
        [HttpPost]
        public IActionResult UpdateExtra(ExtraViewModel vm)
        {
            int id = Convert.ToInt32(TempData["extra"]);
            var extra = _db.Extras.Find(id);

            if (extra is not null && ModelState.IsValid)
            {
                extra.Name = vm.Name;
                extra.Price = vm.Price;

                _db.Extras.Update(extra);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        public IActionResult DeleteExtra(int id)
        {
            var extra = _db.Extras.Find(id);
            _db.Extras.Remove(extra);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult UserOrders()
        {
            var userOrders = _db.Orders.Include(o => o.SelectedMenu).Include(o => o.User).ToList();
            return View(userOrders);
        }
    }
}

HamburgerOrder/Controllers/OrderController.cs
using HamburgerOrder.Data;
using HamburgerOrder.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace HamburgerOrder.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier);
        public OrderController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var products = new ProductsViewModel()
            {
                Extras = _db.Extras.ToList(),
                Menus = _db.Menus.ToList()
            };

            return View(products);
        }
        public IActionResult OrderHistory()
        {
            if (_db.Orders.Include(o => o.SelectedMenu).Where(x => x.UserId == UserId).Count() <= 0)
            {
                ViewBag.Order = "There is no order.";
            }

            var orders = _db.Orders.Include(s => s.SelectedMenu).Where(x => x.UserId == UserId).ToList();

            return View(orders);
        }
        public IActionResult CreateOrder()
        {
            var order = new Order();
            ViewBag.Menus = new SelectList(_db.Menus, "Id", "Name");
            ViewBag.Extras = _db.Extras.ToList();

            order.Calculate();
            return View(order);
        }
        [HttpPost]
        public IActionResult CreateOrder(Order order, List<int> extras)
        {

            order.SelectedMenu = _db.Menus.FirstOrDefault(x => x.Id == order.SelectedMenu.Id);
            order.Extras = _db.Extras.Where(x => extras.Contains(x.Id)).ToList();
            order.UserId = UserId;
            order.Calculate();

            _db.Orders.Add(order);
            _db.SaveChanges();
            return View("OrderInfo", order);

        }
        public IActionResult OrderInfo(Order order, List<int> extras)
        {
            return View(order);
        }
        [HttpPost]
        public IActionResult OrderInfo()
        {
            return RedirectToAction("Index");
        }

        public IActionResult UpdateOrder(int id)
        {
            var order = _db.Orders.Include(o => o.SelectedMenu).Include(o => o.Extras).FirstOrDefault(x => x.Id == id);
            ViewBag.Menus = new SelectList(_db.Menus, "Id", "Name");
            ViewBag.Extras = _db.Extras.ToList();

            return View(order);
        }
        [HttpPost]
        public IActionResult UpdateOrder(Order order, List<int> extras)
        {
            var updatedOrder = _db.Orders.Include(o => o.SelectedMenu).Include(o => o.Extras).FirstOrDefault(x => x.Id == order.Id);
            updatedOrder.SelectedMenu = _db.Menus.Find(order.SelectedMenu.Id);
            updatedOrder.Extras = _db.Extras.Where(e => extras.Contains(e.Id)).ToList();
            updatedOrder.Size = order.Size;
            updatedOrder.Amount = order.Amount;
            updatedOrder.Calculate();

            _db.Update(updatedOrder);
            _db.SaveChanges();

            return View("OrderInfo", updatedOrder);
        }

        public IActionResult DeleteOrder(int id)
        {
            var order = _db.Orders.Include(o => o.SelectedMenu).Include(o => o.Extras).FirstOrDefault(x => x.Id == id);

            _db.Orders.Remove(order);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

HamburgerOrder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BurgerLand</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HamburgerOrder.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BurgerLand</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="OrderHistory">Order History</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="UserOrders">Complated Orders</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BurgerLand - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>